### ISSUE TITLE
당신의 커밋에는 양심이 있나요?

### ISSUE THREAD

**Issue by Goolgae** [songyouhyun/songyouhyun#6]
<img width="187" alt="2021-05-15_18-17-42" src="https://user-images.githubusercontent.com/60869316/118355251-fb96da00-b5a9-11eb-94a2-617beca2efca.png">

정말이지 하나님께 부끄럽지 않은 커밋을 쌓아주셨으면 합니다.

**Comment by songyouhyun** [comment]
하나님은 모든 것을 용서하십니다. 에이맨
